### ISSUE TITLE
Crash with version 1.4

### ISSUE THREAD

**Issue by Blugori** [Tfarcenim/MoreWaterlogging#3]
Hi, minecraft wont load with morewaterlogging 1.4 for 1.16.3

Minecraft ver : 1.16.3
Forge : 34.1.33
MoreWaterLogging : 1.4

I'm using a lot of mods, I'll try to use only more water logging to see what happens

[crash-2020-10-30_18.02.06-client.txt](https://github.com/Tfarcenim/MoreWaterlogging/files/5466568/crash-2020-10-30_18.02.06-client.txt)

**Comment by Blugori** [comment]
[debug.zip](https://github.com/Tfarcenim/MoreWaterlogging/files/5466581/debug.zip)

[latest.zip](https://github.com/Tfarcenim/MoreWaterlogging/files/5466587/latest.zip)

**Comment by Tfarcenim** [comment]
Nope, not more waterlogging

```[30oct.2020 18:00:54.975] [Render thread/DEBUG] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Firing event for modid osv : RegistryEvent.Register<minecraft:worldgen/feature>
[30oct.2020 18:00:54.981] [Render thread/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: Can not register to a locked registry. Modder should use Forge Register methods.
	Index: 2
	Listeners:
		0: NORMAL
		1: ASM: class com.personthecat.orestonevariants.init.RegistryHandler registerOrePlacement(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		2: ASM: class com.personthecat.orestonevariants.init.RegistryHandler registerOreFeatures(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		3: ASM: class com.personthecat.orestonevariants.init.RegistryHandler registerBlocks(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		4: ASM: class com.personthecat.orestonevariants.init.RegistryHandler registerItems(Lnet/minecraftforge/event/RegistryEvent$Register;)V
java.lang.IllegalStateException: Can not register to a locked registry. Modder should use Forge Register methods.
	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:56)
	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:72)
	at net.minecraftforge.registries.NamespacedWrapper.func_218381_a(NamespacedWrapper.java:40)
	at net.minecraft.util.registry.Registry.func_218322_a(Registry.java:456)
	at net.minecraft.util.registry.Registry.func_218325_a(Registry.java:452)
	at com.personthecat.orestonevariants.init.RegistryHandler.registerOreFeatures(RegistryHandler.java:44)
	at net.minecraftforge.eventbus.ASMEventHandler_105_RegistryHandler_registerOreFeatures_Register.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120)
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:111)
	at net.minecraftforge.fml.ModContainer$$Lambda$3313/479788655.run(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618)
	at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56)
	at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40)
	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:242)
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:229)
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:195)
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$1(ClientModLoader.java:103)
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2880/1173015408.run(Unknown Source)
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:123)
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2881/1131932964.run(Unknown Source)
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:103)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:424)
	at net.minecraft.client.main.Main.main(Main.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$492/2107393518.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
```



Go complain to Ore Stone Variants or whatever that mod is

**Comment by Blugori** [comment]
oh what sorry I was sure I uninstalled this mod before reporting, my bad
